service:
  host: http://localhost:8080
  verify_key: 12345678

bot:
  account: 12345678
  database: "./"

Permission:
  Master: 12345678
  DefaultAcceptInvite: true
  Admin: []
  favor: 40
  cd: 30

Debug:
  level: Info

Plugins:
  archiveTalk:
    saveBinary: false

GroupDefaultPluginSwitch:
  pluginSwitch:
    - botSwitch: true
      status: true
      goodTime: true
      hito: true
      randomAcgPic: true
      searchAcgPic: true
      sign: true
      moyu: true
      ill: true
